### ISSUE TITLE
Problem writing to XML file

### ISSUE THREAD

**Issue by pehavens** [joshzelonis/EnterpriseAPT29Eval#1]
Hey Josh. Looking forward to working with your scoring script again.

Unfortunately ran into an issue while writing to XML. Working figuring out the issue. Here are the details of the error I received. Note a number of other folks I work with ran into the same issue...

Traceback (most recent call last):
  File "EnterpriseAPT29Eval.py", line 194, in <module>
    write_xlsx(results)
  File "EnterpriseAPT29Eval.py", line 184, in write_xlsx
    writer.save()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pandas/io/excel/_openpyxl.py", line 43, in save
    return self.book.save(self.path)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/openpyxl/workbook/workbook.py", line 392, in save
    save_workbook(self, filename)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/openpyxl/writer/excel.py", line 293, in save_workbook
    writer.save()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/openpyxl/writer/excel.py", line 275, in save
    self.write_data()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/openpyxl/writer/excel.py", line 89, in write_data
    archive.writestr(ARC_WORKBOOK, writer.write())
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/openpyxl/workbook/_writer.py", line 148, in write
    self.write_views()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/openpyxl/workbook/_writer.py", line 135, in write_views
    active = get_active_sheet(self.wb)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/openpyxl/workbook/_writer.py", line 33, in get_active_sheet
    raise IndexError("At least one sheet must be visible")
IndexError: At least one sheet must be visible

**Comment by danilomichelucci** [comment]
Same here...

**Comment by pehavens** [comment]
By the way, if I pip3 install xlsxwriter, the error goes away, but I still end up with a blank xlsx file of about 5k.

**Comment by joshzelonis** [comment]
I had two issues, my data/ dir didn't end up in the build and the requirements.txt was broken.

I believe the issue should be resolved with a fresh clone.

**Comment by joshzelonis** [comment]
confirmed resolved via twitter
